Docs/add flashloan examples
White-Whale-Defi-Platform/white-whale-docs pull request #15
Opened 2022-12-06 15:44 UTC by SirTLB

2022-12-06 21:22 UTC, kaimen-sano approved these changes, later dismissed
Overall this is a great addition to our docs to explain how flashloans work, love the step-by-step walkthrough of the flashloan example

2022-12-06 21:22 UTC, kaimen-sano commented on client-docs/flashloan.md
> +A very important property of this contract is that it is able to "route" the requested asset by the user to the right vault, thus, we only need **one** flashloan router contract for all vaults deploy
Maybe below this we could also discuss how the router automatically returns profits back to the user? This is also something that enables users to use the flashloan router very easily without having to deploy a contract.

2022-12-06 21:22 UTC, kaimen-sano commented on client-docs/flashloan.md
> +Every entry in `Msgs` should have the following format:
Maybe specify that every `WasmExecuteMessage` should be in this format? Because you can also do things like `Bank` send messages - not just wasm execute messages.

2022-12-06 21:22 UTC, kaimen-sano commented on package.json
> +    "graceful-fs": "^4.2.4"
How come this was added as a dependency? In both `dependencies` and `devDependencies`?

2022-12-07 15:22 UTC, SirTLB commented on package.json
> +    "graceful-fs": "^4.2.4"
no clue, try to run gitbook locally gives me headaches. Can remove these i guess

2022-12-08 08:52 UTC, SirTLB commented on client-docs/flashloan.md
> +A very important property of this contract is that it is able to "route" the requested asset by the user to the right vault, thus, we only need **one** flashloan router contract for all vaults deploy
good one

2022-12-08 11:20 UTC, SirTLB commented on package.json
> +    "graceful-fs": "^4.2.4"
fixed

2022-12-08 23:22 UTC, kaimen-sano requested changes
Final last things, overall good though

2022-12-08 23:22 UTC, kaimen-sano commented on client-docs/flashloan.md
> +However this might as well be an BankSendMessage:
```suggestion
Any `CosmosMsg` is able to be sent, so it is also possible to have a bank send message in the flashloan router.
```

2022-12-08 23:22 UTC, kaimen-sano commented on client-docs/flashloan.md
> +However this might as well be an BankSendMessage:
Maybe something like this is a bit more clear?

2022-12-09 12:27 UTC, Sen-Com approved these changes, later dismissed

2022-12-09 16:23 UTC, 0xFable approved these changes, later dismissed
Changes LGTM, had a proper read, can ignore most of the nitpicky comments

2022-12-09 16:23 UTC, 0xFable commented on gitbook/client-docs/flashloan.md
> +The White Whale Flashloan operation is a specific property of each of the [Vaults](/smart-contracts/liquidity-hub/vault-network/vault.md) deployed by White Whale. However, these flashloan messages ar
nit: remove 'So, '

2022-12-09 16:23 UTC, 0xFable commented on gitbook/client-docs/flashloan.md
> +The Msgs holds all messages that the contract should execute sequentially. Meaning it will first execute the first message, then the second and so on. This gives the opportunity to use the results fr
Msgs field holds all...

2022-12-09 16:23 UTC, 0xFable commented on gitbook/client-docs/flashloan_example.md
> +A very important distinction to make here is that we do not fill the `funds` field. We are swapping ASTRO (which we obtained from message 2) into Luna (which we borrowed), means our cyclic arbitrage
Very good to point this out, was looking for this

2022-12-09 16:23 UTC, 0xFable commented on gitbook/client-docs/flashloan_example.md
> +```typescript
Not needed now but this section could be bigger, maybe a full guide on executing outside the webapp.

2022-12-10 13:32 UTC, Sen-Com approved these changes

2022-12-10 18:48 UTC, merged

2022-12-10 18:49 UTC, kerber0x commented
Great job sit 🌟