feat(denoms): Add 2 simple tables with asset info
White-Whale-Defi-Platform/white-whale-docs pull request #54
Opened 2023-04-28 12:11 UTC by 0xFable

2023-04-28 12:44 UTC, kerber0x requested changes
Awesome addition, here are some improvements though

2023-04-28 12:44 UTC, kerber0x commented on gitbook/smart-contracts/assets /denoms.md
> +## Migaloo on each zone
```suggestion
## Whale on each zone
```

2023-04-28 12:44 UTC, kerber0x commented on gitbook/smart-contracts/assets /denoms.md
> +## Migaloo on each zone
This refers to the whale token right?

2023-04-28 12:44 UTC, kerber0x commented on gitbook/smart-contracts/assets /denoms.md
> +| Migaloo    | uwhale                                                                             |   [![WHALE logo](https://raw.githubusercontent.com/cosmos/chain-registry/master/migaloo/images/whit
Terra is missing sir `ibc/36A02FFC4E74DF4F64305130C3DFA1B06BEAC775648927AA44467C76A77AB8DB`

2023-05-02 17:04 UTC, 0xFable commented
Thank you for review @kerber0x, just noticed it when opening another PR. I took care of and pushed the requested changes there 🙏

2023-05-03 10:03 UTC, kerber0x approved these changes
Lovely, well done! very useful indeed!

2023-05-03 10:03 UTC, merged